trading_task:
  description: >
    Analyse {stock_symbol} market data, with {order_size}, propose a justified order (BUY/SELL/HOLD),
    based on this {max_risk} and liquidity assessment.

  expected_output: >
    A clear order (BUY/SELL/HOLD) with a justification based on the current price and 5-day variation.
  
risk_manager_task:
  description: >
    Assess the robustness and volatility of the Trader's proposal for {stock_symbol} and detect excessive risks.
    use risk_rules.pdf to check any specific risk criteria restrictions.

  expected_output: >
    An assessment of the proposed order's risk level, including historical volatility and beta analysis. 
    A recommendation to approve or reject the order based on risk criteria.

compliance_task:
  description: >
    Ensure the Trader's proposal for {stock_symbol} adheres to regulatory standards and internal policies.
    Use the compliance_rules.pdf to check restrictions, especially regarding GAFAM stocks
    and the rule that orders larger than 50 shares MUST be rejected.
  expected_output: >
    A compliance report verifying that the proposed order complies with all relevant regulations and company policies,
    including any necessary adjustments or rejections.

summary_task:
  description: >
    Summarize the entire decision-making process for {stock_symbol}, including the trader's proposal, risk assessment, and compliance check.  
  expected_output: >
    A final summary of the trading decision, highlighting key points from each agent's analysis and the final order decision.
    Format the output in markdown with important points in bold.