meal_planning_task:
  description: >
    Search for the best '{meal_name}' recipe for {servings} people within a {budget} budget.
    Consider dietary restrictions: {dietary_restrictions} and cooking skill level: {cooking_skill}.
    Find recipes that match the skill level and provide complete ingredient lists with quantities.

  expected_output: >
    A detailed meal plan with researched ingredients, quantities, and cooking instructions 
    appropriate for the skill level.
  
shopping_organizer_task:
  description: >
    Organize the ingredients from the '{meal_name}' meal plan into a grocery shopping list.
    Group items by store sections (Produce, Dairy, Meat, Pantry).
    Estimate quantities for {servings} people.
    Consider dietary restrictions: {dietary_restrictions}, cooking skill: {cooking_skill}, and respect the budget: {budget}.

  expected_output: >
    Return ONLY a valid JSON object strictly as shopping list grouped by store sections with quantities and prices.


budget_advisor_task:
  description: >
    Analyze the shopping plan for '{meal_name}' serving {servings} people.
    Ensure total cost stays within {budget}. Consider dietary restrictions: {dietary_restrictions}.
    Provide practical money-saving tips and alternative ingredients if needed to meet budget.

  expected_output: >
    A complete shopping guide with detailed prices, budget analysis, and money-saving tips.

leftover_task:
  description: >
    Analyze the shopping list for '{meal_name}' and identify ingredients that might result in leftovers or partial usage. 
    Suggest additional quick meals or recipes that can use these leftover ingredients within the {budget} budget.
    Consider dietary restrictions: {dietary_restrictions}.
  expected_output: >
    A list of bonus recipes and creative uses for leftover ingredients, helping to maximize the grocery budget and minimize waste.

summary_task:
  description: >  
    Compile a comprehensive meal planning report for '{meal_name}' serving {servings} people.
    Include the meal plan, organized shopping list, budget analysis, money-saving tips, and leftover management strategies.
    Ensure all dietary restrictions: {dietary_restrictions}, cooking skill: {cooking_skill}, and budget: {budget} are respected.    
  expected_output: >
    A comprehensive meal planning guide that combines all team outputs into one cohesive report.